---
- name: Copy forwarding configuration file
  ansible.builtin.template:
    src: forwarding.conf.j2
    dest: /etc/firewall/forwarding.conf
    mode: '0640'
    owner: root
    group: root
  notify:
    - Restart firewall service
