---
- name: Copy ip-blacklist configuration file
  ansible.builtin.template:
    src: ip-blacklist.conf.j2
    dest: /etc/firewall/ip-blacklist.conf
    mode: '0640'
    owner: root
    group: root
  notify:
    - Restart firewall service
