---
- name: Copy services configuration file
  ansible.builtin.template:
    src: services.conf.j2
    dest: /etc/firewall/services.conf
    mode: '0640'
    owner: root
    group: root
  notify:
    - Restart firewall service
